services:
  - type: web
    name: appraisal-app
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_SUPABASE_ENCRYPTION_KEY
        sync: false
      - key: VITE_MSAL_CLIENT_ID
        sync: false
      - key: VITE_MSAL_TENANT_ID
        sync: false
    # Use the Dockerfile in the root directory
    dockerfilePath: ./Dockerfile
    dockerContext: .
